# Model Creation (Polars)

## Initialisation

In [1]:
# Run this block of codes before running the individual models.
from sklearn.model_selection import train_test_split
# Custom import
from get_dataset_polars import get_polars_df
from pipes_and_transformers_polars import get_pipeline_polars

# Gets Polars dataframe.
raw = get_polars_df()

y = raw.select("price")
X_train, X_test, y_train, y_test = train_test_split(raw, y, test_size=0.2, random_state=42)

## Dummy Model

In [2]:
from sklearn.dummy import DummyRegressor

dummy = DummyRegressor(strategy="mean")

# Gets pipe.
"""
Following code has been shifted to pipes_and_transformers_polars.py for reuse with other models.

input_model = Pipeline(steps=[('tweak', tweak_transformer),
                      ('zip_avg_price', ZipAvgPriceAdder()),
                      ('preprocessor', preprocessor),
                      ('input_model', input_model),
                      ])
"""

dummy_pipe = get_pipeline_polars(dummy)
dummy_pipe.fit(X_train, y_train)

print(dummy_pipe.score(X_test, y_test))

-0.000889991449168015


In [3]:
dummy_pipe

,"steps steps: list of tuplesList of (name of step, estimator) tuples that are to be chained insequential order. To be compatible with the scikit-learn API, all stepsmust define `fit`. All non-last steps must also define `transform`. See:ref:`Combining Estimators ` for more details.","[('tweak', ...), ('zip_avg_price', ...), ...]"
,"transform_input transform_input: list of str, default=NoneThe names of the :term:`metadata` parameters that should be transformed by thepipeline before passing it to the step consuming it.This enables transforming some input arguments to ``fit`` (other than ``X``)to be transformed by the steps of the pipeline up to the step which requiresthem. Requirement is defined via :ref:`metadata routing `.For instance, this can be used to pass a validation set through the pipeline.You can only set this if metadata routing is enabled, which youcan enable using ``sklearn.set_config(enable_metadata_routing=True)``... versionadded:: 1.6",None
,"memory memory: str or object with the joblib.Memory interface, default=NoneUsed to cache the fitted transformers of the pipeline. The last stepwill never be cached, even if it is a transformer. By default, nocaching is performed. If a string is given, it is the path to thecaching directory. Enabling caching triggers a clone of the transformersbefore fitting. Therefore, the transformer instance given to thepipeline cannot be inspected directly. Use the attribute ``named_steps``or ``steps`` to inspect estimators within the pipeline. Caching thetransformers is advantageous when fitting is time consuming. See:ref:`sphx_glr_auto_examples_neighbors_plot_caching_nearest_neighbors.py`for an example on how to enable caching.",None
,"verbose verbose: bool, default=FalseIf True, the time elapsed while fitting each step will be printed as itis completed.",False
,"func func: callable, default=NoneThe callable to use for the transformation. This will be passedthe same arguments as transform, with args and kwargs forwarded.If func is None, then func will be the identity function.",<function twe...00214EC588F40>
,"inverse_func inverse_func: callable, default=NoneThe callable to use for the inverse transformation. This will bepassed the same arguments as inverse transform, with args andkwargs forwarded. If inverse_func is None, then inverse_funcwill be the identity function.",None
,"validate validate: bool, default=FalseIndicate that the input X array should be checked before calling``func``. The possibilities are:- If False, there is no input validation.- If True, then X will be converted to a 2-dimensional NumPy array or sparse matrix. If the conversion is not possible an exception is raised... versionchanged:: 0.22 The default of ``validate`` changed from True to False.",False
,"accept_sparse accept_sparse: bool, default=FalseIndicate that func accepts a sparse matrix as input. If validate isFalse, this has no effect. Otherwise, if accept_sparse is false,sparse matrix inputs will cause an exception to be raised.",False
,"check_inverse check_inverse: bool, default=TrueWhether to check that or ``func`` followed by ``inverse_func`` leads tothe original inputs. It can be used for a sanity check, raising awarning when the condition is not fulfilled... versionadded:: 0.20",True
,"feature_names_out feature_names_out: callable, 'one-to-one' or None, default=NoneDetermines the list of feature names that will be returned by the`get_feature_names_out` method. If it is 'one-to-one', then the outputfeature names will be equal to the input feature names. If it is acallable, then it must take two positional arguments: this`FunctionTransformer` (`self`) and an array-like of input feature names(`input_features`). It must return an array-like of output featurenames. The `get_feature_names_out` method is only defined if`feature_names_out` is not None.See ``get_feature_names_out`` for more details... versionadded:: 1.1",None
,"kw_args kw_args: dict, default=NoneDictionary of additional keyword arguments to

In [4]:
# For Python's IDLE
print(dummy_pipe)

Pipeline(steps=[('tweak',
                 FunctionTransformer(func=<function tweak_housing at 0x00000214EC588F40>)),
                ('zip_avg_price', ZipAvgPriceAdder()),
                ('preprocessor',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  ['bedrooms', 'bathrooms',
                                                   'sqft_living', 'sqft_lot',
                                                   'floors', 'waterfront',
                                                   'view', 'condition', 'grade',
                                                   'sqft_above',
                 

In [5]:
dummy_pipe.predict(X_test)

array([537768.04794679, 537768.04794679, 537768.04794679, ...,
       537768.04794679, 537768.04794679, 537768.04794679], shape=(4323,))

In [6]:
# For Python's IDLE
print(dummy_pipe.predict(X_test))

[537768.04794679 537768.04794679 537768.04794679 ... 537768.04794679
 537768.04794679 537768.04794679]


## Linear Regression

In [7]:
from sklearn.linear_model import LinearRegression

lr =  LinearRegression()
lr_pipe = get_pipeline_polars(lr)
lr_pipe.fit(X_train, y_train)
print(lr_pipe.score(X_test, y_test))

0.8069700278216327


In [8]:
lr_pipe.predict(X_test)

array([[ 371567.34403357],
       [ 828686.21791615],
       [1240732.76086806],
       ...,
       [ 380806.40648027],
       [ 665643.84974678],
       [ 383961.75794695]], shape=(4323, 1))

In [9]:
# For Python's IDLE
print(lr_pipe.predict(X_test))

[[ 371567.34403357]
 [ 828686.21791615]
 [1240732.76086806]
 ...
 [ 380806.40648027]
 [ 665643.84974678]
 [ 383961.75794695]]


## Decision Trees

In [10]:
from sklearn.tree import DecisionTreeRegressor

dt = DecisionTreeRegressor()
dt_pipe = get_pipeline_polars(dt)
dt_pipe.fit(X_train, y_train)

,"steps steps: list of tuplesList of (name of step, estimator) tuples that are to be chained insequential order. To be compatible with the scikit-learn API, all stepsmust define `fit`. All non-last steps must also define `transform`. See:ref:`Combining Estimators ` for more details.","[('tweak', ...), ('zip_avg_price', ...), ...]"
,"transform_input transform_input: list of str, default=NoneThe names of the :term:`metadata` parameters that should be transformed by thepipeline before passing it to the step consuming it.This enables transforming some input arguments to ``fit`` (other than ``X``)to be transformed by the steps of the pipeline up to the step which requiresthem. Requirement is defined via :ref:`metadata routing `.For instance, this can be used to pass a validation set through the pipeline.You can only set this if metadata routing is enabled, which youcan enable using ``sklearn.set_config(enable_metadata_routing=True)``... versionadded:: 1.6",None
,"memory memory: str or object with the joblib.Memory interface, default=NoneUsed to cache the fitted transformers of the pipeline. The last stepwill never be cached, even if it is a transformer. By default, nocaching is performed. If a string is given, it is the path to thecaching directory. Enabling caching triggers a clone of the transformersbefore fitting. Therefore, the transformer instance given to thepipeline cannot be inspected directly. Use the attribute ``named_steps``or ``steps`` to inspect estimators within the pipeline. Caching thetransformers is advantageous when fitting is time consuming. See:ref:`sphx_glr_auto_examples_neighbors_plot_caching_nearest_neighbors.py`for an example on how to enable caching.",None
,"verbose verbose: bool, default=FalseIf True, the time elapsed while fitting each step will be printed as itis completed.",False
,"func func: callable, default=NoneThe callable to use for the transformation. This will be passedthe same arguments as transform, with args and kwargs forwarded.If func is None, then func will be the identity function.",<function twe...00214EC588F40>
,"inverse_func inverse_func: callable, default=NoneThe callable to use for the inverse transformation. This will bepassed the same arguments as inverse transform, with args andkwargs forwarded. If inverse_func is None, then inverse_funcwill be the identity function.",None
,"validate validate: bool, default=FalseIndicate that the input X array should be checked before calling``func``. The possibilities are:- If False, there is no input validation.- If True, then X will be converted to a 2-dimensional NumPy array or sparse matrix. If the conversion is not possible an exception is raised... versionchanged:: 0.22 The default of ``validate`` changed from True to False.",False
,"accept_sparse accept_sparse: bool, default=FalseIndicate that func accepts a sparse matrix as input. If validate isFalse, this has no effect. Otherwise, if accept_sparse is false,sparse matrix inputs will cause an exception to be raised.",False
,"check_inverse check_inverse: bool, default=TrueWhether to check that or ``func`` followed by ``inverse_func`` leads tothe original inputs. It can be used for a sanity check, raising awarning when the condition is not fulfilled... versionadded:: 0.20",True
,"feature_names_out feature_names_out: callable, 'one-to-one' or None, default=NoneDetermines the list of feature names that will be returned by the`get_feature_names_out` method. If it is 'one-to-one', then the outputfeature names will be equal to the input feature names. If it is acallable, then it must take two positional arguments: this`FunctionTransformer` (`self`) and an array-like of input feature names(`input_features`). It must return an array-like of output featurenames. The `get_feature_names_out` method is only defined if`feature_names_out` is not None.See ``get_feature_names_out`` for more details... versionadded:: 1.1",None
,"kw_args kw_args: dict, default=NoneDictionary of additional keyword arguments to

In [11]:
# Sets max_depth=1
dt_pipe.set_params(model__max_depth=1)
dt_pipe.fit(X_train, y_train)
print(dt_pipe.score(X_test, y_test))

0.31051544204266734


In [14]:
# Sets max_depth=9
dt_pipe.set_params(model__max_depth=9)
dt_pipe.fit(X_train, y_train)
print(dt_pipe.score(X_test, y_test))

0.7498770261640668


## CatBoost

In [15]:
from catboost import CatBoostRegressor

cat = CatBoostRegressor()
cat_pipe = get_pipeline_polars(cat)
cat_pipe.fit(X_train, y_train.to_numpy()[:,0])

print(cat_pipe.score(X_test, y_test.to_numpy()[:,0]))

Learning rate set to 0.064232
0:	learn: 346982.2594620	total: 2.5ms	remaining: 2.49s
1:	learn: 332378.5598059	total: 4.65ms	remaining: 2.32s
2:	learn: 319502.6617458	total: 6.96ms	remaining: 2.31s
3:	learn: 307490.7902475	total: 9.11ms	remaining: 2.27s
4:	learn: 294940.3225791	total: 11.2ms	remaining: 2.23s
5:	learn: 283907.9796375	total: 13.4ms	remaining: 2.22s
6:	learn: 273592.5548762	total: 15.4ms	remaining: 2.19s
7:	learn: 263472.9134855	total: 17.6ms	remaining: 2.18s
8:	learn: 254884.3331936	total: 19.6ms	remaining: 2.15s
9:	learn: 246261.9209853	total: 21.8ms	remaining: 2.16s
10:	learn: 238183.5765242	total: 23.9ms	remaining: 2.15s
11:	learn: 230600.1564374	total: 26ms	remaining: 2.14s
12:	learn: 223779.4367347	total: 28.2ms	remaining: 2.14s
13:	learn: 217021.8170437	total: 30.4ms	remaining: 2.14s
14:	learn: 210875.7711670	total: 32.5ms	remaining: 2.13s
15:	learn: 205122.1910805	total: 34.6ms	remaining: 2.13s
16:	learn: 199643.2642325	total: 36.9ms	remaining: 2.13s
17:	learn: 194